Implemented QFP80 component
tscircuit/jscad-electronics pull request #40
Opened 2024-09-21 17:50 UTC by abhijitxy

#39

2024-09-21 17:50 UTC, seveibar commented on lib/qfp80.tsx
> +import { ChipBody } from "./ChipBody";
the file name should just be `qfp`

2024-09-21 17:51 UTC, seveibar requested changes
not sure why you introduced a new file in the `lib` dir

2024-09-21 17:55 UTC, abhijitxy commented
> not sure why you introduced a new file in the `lib` dir

So they have a different body width

2024-09-21 18:09 UTC, seveibar requested changes

2024-09-21 18:09 UTC, seveibar commented on lib/qfp.tsx
> +  fullWidth = pinCount === 80 ? 14 : 10,
hmm this is a hack, you should derive the width automatically, we shouldn't hard code width values

2024-09-22 16:03 UTC, seveibar approved these changes

2024-09-22 16:19 UTC, merged